"""食材マスタデータ。

RAGノーマライザー (normalizer.py) がこのデータをSQLiteに投入し、
ベクトル検索・ファジーマッチの対象として使用する。

各エントリのフィールド:
  canonical       : 正規名（在庫DBに記録される標準名称）
  aliases         : 別名リスト（商品名・地方名・カタカナ表記など）
  category        : カテゴリ（db.CATEGORIES に合わせる）
  shelf_life_days : 冷蔵保存の標準日数（None は長期保存可）
"""

FOOD_MASTER: list[dict] = [
    # ── 鶏肉 ──────────────────────────────────────────────────────────────────
    {"canonical": "鶏もも肉",
     "aliases": ["チキンもも", "鶏モモ", "とりもも", "もも肉", "チキン腿", "鳥もも"],
     "category": "肉・魚", "shelf_life_days": 3},
    {"canonical": "鶏むね肉",
     "aliases": ["チキンむね", "鶏ムネ", "とりむね", "むね肉", "チキンブレスト", "鳥むね"],
     "category": "肉・魚", "shelf_life_days": 3},
    {"canonical": "鶏ひき肉",
     "aliases": ["とりひき", "チキンミンチ", "鶏挽き肉", "鶏ミンチ"],
     "category": "肉・魚", "shelf_life_days": 1},
    {"canonical": "鶏手羽元",
     "aliases": ["手羽元", "チキン手羽元", "鶏手羽"],
     "category": "肉・魚", "shelf_life_days": 3},

    # ── 豚肉 ──────────────────────────────────────────────────────────────────
    {"canonical": "豚バラ肉",
     "aliases": ["ポークバラ", "豚バラ", "バラ肉", "豚三枚肉", "五花肉"],
     "category": "肉・魚", "shelf_life_days": 3},
    {"canonical": "豚こま切れ肉",
     "aliases": ["豚こま", "豚切り落とし", "豚コマ", "ポークこま", "豚うす切り"],
     "category": "肉・魚", "shelf_life_days": 3},
    {"canonical": "豚ロース肉",
     "aliases": ["ポークロース", "豚ロース", "とんかつ用豚肉", "豚ステーキ肉"],
     "category": "肉・魚", "shelf_life_days": 3},
    {"canonical": "豚ひき肉",
     "aliases": ["ポークミンチ", "豚挽き肉", "豚ミンチ"],
     "category": "肉・魚", "shelf_life_days": 1},

    # ── 牛肉・合挽き ───────────────────────────────────────────────────────────
    {"canonical": "牛こま切れ肉",
     "aliases": ["牛こま", "牛切り落とし", "ビーフこま", "牛うす切り"],
     "category": "肉・魚", "shelf_life_days": 3},
    {"canonical": "合いびき肉",
     "aliases": ["合挽き", "ミックスミンチ", "合い挽き", "あいびき", "牛豚合挽き"],
     "category": "肉・魚", "shelf_life_days": 1},

    # ── 加工肉 ────────────────────────────────────────────────────────────────
    {"canonical": "ベーコン",
     "aliases": ["スモークベーコン", "厚切りベーコン", "ハーフベーコン"],
     "category": "肉・魚", "shelf_life_days": 7},
    {"canonical": "ウインナー",
     "aliases": ["ソーセージ", "フランクフルト", "ウィンナー", "ウインナーソーセージ"],
     "category": "肉・魚", "shelf_life_days": 7},
    {"canonical": "ハム",
     "aliases": ["ロースハム", "ボンレスハム", "スライスハム"],
     "category": "肉・魚", "shelf_life_days": 7},

    # ── 魚介類 ────────────────────────────────────────────────────────────────
    {"canonical": "サーモン",
     "aliases": ["鮭", "サーモントラウト", "スモークサーモン", "アトランティックサーモン", "トラウトサーモン"],
     "category": "肉・魚", "shelf_life_days": 2},
    {"canonical": "マグロ",
     "aliases": ["まぐろ", "本マグロ", "ビンチョウマグロ", "メバチマグロ", "キハダマグロ"],
     "category": "肉・魚", "shelf_life_days": 1},
    {"canonical": "アジ",
     "aliases": ["あじ", "真アジ", "アジの開き", "アジフライ用"],
     "category": "肉・魚", "shelf_life_days": 2},
    {"canonical": "サバ",
     "aliases": ["さば", "真さば", "ゴマさば", "塩さば", "サバの切り身"],
     "category": "肉・魚", "shelf_life_days": 2},
    {"canonical": "エビ",
     "aliases": ["えび", "海老", "バナメイエビ", "ブラックタイガー", "むきえび", "冷凍エビ"],
     "category": "肉・魚", "shelf_life_days": 2},
    {"canonical": "イカ",
     "aliases": ["いか", "スルメイカ", "ヤリイカ", "ケンサキイカ"],
     "category": "肉・魚", "shelf_life_days": 2},
    {"canonical": "アサリ",
     "aliases": ["あさり", "はまぐり", "しじみ", "貝類"],
     "category": "肉・魚", "shelf_life_days": 2},

    # ── 野菜（根菜・長期保存） ────────────────────────────────────────────────
    {"canonical": "玉ねぎ",
     "aliases": ["たまねぎ", "オニオン", "新玉ねぎ", "淡路玉ねぎ", "淡路たまねぎ", "ペコロス"],
     "category": "野菜", "shelf_life_days": 30},
    {"canonical": "にんじん",
     "aliases": ["人参", "ニンジン", "キャロット", "ベビーキャロット", "人蔘"],
     "category": "野菜", "shelf_life_days": 14},
    {"canonical": "じゃがいも",
     "aliases": ["馬鈴薯", "ジャガイモ", "ポテト", "メークイン", "男爵いも", "きたあかり"],
     "category": "野菜", "shelf_life_days": 21},
    {"canonical": "大根",
     "aliases": ["だいこん", "ダイコン", "カット大根", "青首大根"],
     "category": "野菜", "shelf_life_days": 14},
    {"canonical": "さつまいも",
     "aliases": ["サツマイモ", "紅はるか", "安納芋", "鳴門金時"],
     "category": "野菜", "shelf_life_days": 21},
    {"canonical": "にんにく",
     "aliases": ["ガーリック", "ニンニク", "青森にんにく", "黒にんにく"],
     "category": "野菜", "shelf_life_days": 30},
    {"canonical": "生姜",
     "aliases": ["しょうが", "ショウガ", "ジンジャー", "新生姜", "土しょうが"],
     "category": "野菜", "shelf_life_days": 21},

    # ── 野菜（葉物・短期） ────────────────────────────────────────────────────
    {"canonical": "キャベツ",
     "aliases": ["春キャベツ", "グリーンキャベツ", "カット野菜（キャベツ）"],
     "category": "野菜", "shelf_life_days": 7},
    {"canonical": "白菜",
     "aliases": ["はくさい", "ハクサイ", "カット白菜", "中国白菜"],
     "category": "野菜", "shelf_life_days": 7},
    {"canonical": "ほうれん草",
     "aliases": ["ほうれんそう", "ホウレンソウ", "冷凍ほうれん草"],
     "category": "野菜", "shelf_life_days": 4},
    {"canonical": "小松菜",
     "aliases": ["こまつな", "コマツナ", "冬菜"],
     "category": "野菜", "shelf_life_days": 4},
    {"canonical": "長ねぎ",
     "aliases": ["ねぎ", "ネギ", "白ねぎ", "白ネギ", "深谷ねぎ", "万能ねぎ", "小ねぎ"],
     "category": "野菜", "shelf_life_days": 7},
    {"canonical": "もやし",
     "aliases": ["豆もやし", "緑豆もやし", "大豆もやし"],
     "category": "野菜", "shelf_life_days": 2},
    {"canonical": "トマト",
     "aliases": ["とまと", "ミニトマト", "チェリートマト", "フルーツトマト", "中玉トマト"],
     "category": "野菜", "shelf_life_days": 7},
    {"canonical": "きゅうり",
     "aliases": ["キュウリ", "胡瓜", "ミニきゅうり"],
     "category": "野菜", "shelf_life_days": 5},
    {"canonical": "なす",
     "aliases": ["ナス", "茄子", "米なす", "長なす"],
     "category": "野菜", "shelf_life_days": 5},
    {"canonical": "ピーマン",
     "aliases": ["パプリカ", "赤パプリカ", "黄パプリカ", "緑ピーマン"],
     "category": "野菜", "shelf_life_days": 7},
    {"canonical": "ブロッコリー",
     "aliases": ["カリフラワー", "茎ブロッコリー", "冷凍ブロッコリー"],
     "category": "野菜", "shelf_life_days": 5},

    # ── きのこ類 ──────────────────────────────────────────────────────────────
    {"canonical": "しいたけ",
     "aliases": ["椎茸", "シイタケ", "原木しいたけ", "干し椎茸"],
     "category": "野菜", "shelf_life_days": 5},
    {"canonical": "しめじ",
     "aliases": ["ぶなしめじ", "ブナシメジ", "しめじ（パック）"],
     "category": "野菜", "shelf_life_days": 5},
    {"canonical": "えのき",
     "aliases": ["えのきだけ", "エノキ", "エノキタケ"],
     "category": "野菜", "shelf_life_days": 5},

    # ── 果物 ──────────────────────────────────────────────────────────────────
    {"canonical": "りんご",
     "aliases": ["リンゴ", "林檎", "ふじりんご", "サンふじ", "つがる"],
     "category": "果物", "shelf_life_days": 14},
    {"canonical": "バナナ",
     "aliases": ["ばなな", "フィリピンバナナ", "国産バナナ"],
     "category": "果物", "shelf_life_days": 5},
    {"canonical": "みかん",
     "aliases": ["温州みかん", "オレンジ", "マンダリン", "柑橘"],
     "category": "果物", "shelf_life_days": 14},
    {"canonical": "いちご",
     "aliases": ["苺", "イチゴ", "あまおう", "とちおとめ", "紅ほっぺ"],
     "category": "果物", "shelf_life_days": 3},
    {"canonical": "ぶどう",
     "aliases": ["葡萄", "ブドウ", "マスカット", "巨峰", "ピオーネ"],
     "category": "果物", "shelf_life_days": 5},

    # ── 乳製品 ────────────────────────────────────────────────────────────────
    {"canonical": "牛乳",
     "aliases": ["ミルク", "低脂肪乳", "成分調整牛乳", "ノンホモ牛乳", "乳飲料"],
     "category": "乳製品", "shelf_life_days": 7},
    {"canonical": "ヨーグルト",
     "aliases": ["プレーンヨーグルト", "ギリシャヨーグルト", "無糖ヨーグルト", "飲むヨーグルト"],
     "category": "乳製品", "shelf_life_days": 14},
    {"canonical": "バター",
     "aliases": ["有塩バター", "無塩バター", "発酵バター", "食塩不使用バター"],
     "category": "乳製品", "shelf_life_days": 30},
    {"canonical": "チーズ",
     "aliases": ["スライスチーズ", "プロセスチーズ", "クリームチーズ", "モッツァレラ", "シュレッドチーズ"],
     "category": "乳製品", "shelf_life_days": 14},
    {"canonical": "生クリーム",
     "aliases": ["ホイップクリーム", "植物性クリーム", "動物性生クリーム", "乳脂肪クリーム"],
     "category": "乳製品", "shelf_life_days": 5},

    # ── 卵・豆腐・大豆製品 ───────────────────────────────────────────────────
    {"canonical": "卵",
     "aliases": ["たまご", "鶏卵", "Mサイズ卵", "Lサイズ卵", "特大卵", "赤玉"],
     "category": "卵", "shelf_life_days": 21},
    {"canonical": "豆腐",
     "aliases": ["絹豆腐", "木綿豆腐", "充填豆腐", "ソフト豆腐", "絹ごし豆腐"],
     "category": "その他", "shelf_life_days": 4},
    {"canonical": "納豆",
     "aliases": ["ひきわり納豆", "小粒納豆", "大粒納豆", "糸引き納豆"],
     "category": "その他", "shelf_life_days": 4},
    {"canonical": "豆乳",
     "aliases": ["無調整豆乳", "調整豆乳", "成分無調整豆乳"],
     "category": "乳製品", "shelf_life_days": 7},

    # ── 穀物・炭水化物 ────────────────────────────────────────────────────────
    {"canonical": "米",
     "aliases": ["お米", "白米", "玄米", "コシヒカリ", "あきたこまち", "ひとめぼれ"],
     "category": "穀物", "shelf_life_days": None},
    {"canonical": "食パン",
     "aliases": ["パン", "ロールパン", "バゲット", "クロワッサン", "山型食パン"],
     "category": "穀物", "shelf_life_days": 5},
    {"canonical": "うどん",
     "aliases": ["冷凍うどん", "生うどん", "乾麺うどん", "さぬきうどん"],
     "category": "穀物", "shelf_life_days": 3},
    {"canonical": "パスタ",
     "aliases": ["スパゲッティ", "スパゲティ", "フェットチーネ", "ペンネ", "乾麺パスタ"],
     "category": "穀物", "shelf_life_days": None},

    # ── 調味料 ────────────────────────────────────────────────────────────────
    {"canonical": "醤油",
     "aliases": ["しょうゆ", "ショウユ", "濃口醤油", "薄口醤油", "たまり醤油", "だし醤油"],
     "category": "調味料", "shelf_life_days": 180},
    {"canonical": "みりん",
     "aliases": ["本みりん", "みりん風調味料", "料理みりん"],
     "category": "調味料", "shelf_life_days": 180},
    {"canonical": "料理酒",
     "aliases": ["酒", "清酒", "日本酒", "白ワイン（料理用）", "調理酒"],
     "category": "調味料", "shelf_life_days": 180},
    {"canonical": "味噌",
     "aliases": ["みそ", "赤みそ", "白みそ", "合わせみそ", "信州みそ"],
     "category": "調味料", "shelf_life_days": 90},
    {"canonical": "マヨネーズ",
     "aliases": ["マヨ", "キューピーマヨ", "カロリーハーフマヨ"],
     "category": "調味料", "shelf_life_days": 60},
    {"canonical": "ケチャップ",
     "aliases": ["トマトケチャップ", "トマトソース", "チリソース"],
     "category": "調味料", "shelf_life_days": 60},
]
